{
 "title": "Demo1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job, status) (\n  rate(\n    {job=\"gin-app\"}\n    | json\n    | status=~\"2..|4..|5..\"\n    [${__interval:5m}]\n  )\n)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    count_over_time(\n      {job=\"gin-app\"} \n      | json \n      | status=~\"2..\" \n      [$__range]\n    )\n  )\n  /\n  sum(\n    count_over_time(\n      {job=\"gin-app\"} \n      | json \n      | method=\"GET\" \n      [$__range]\n    )\n  )\n) * 100"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"gin-app\"} | json | method=\"GET\" [$__range]\n  )\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Success Calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (\n  count_over_time({job=\"gin-app\"} | json | status=~\"2..\" [$__range])\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Num Warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (\n  count_over_time({job=\"gin-app\"} | json | status=~\"4..\" [$__range])\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Num Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"gin-app\"} \n    | json \n    | status=~\"5..\" \n    [$__range]\n  )\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "5xx Endpoints",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"gin-app\"} | json\n    | status=~\"5..\""
    }
   ]
  }
 ]
}